### ISSUE TITLE
Can't finish a level with more than 2 people

### ISSUE THREAD

**Issue by mikewenk** [kyleraykbs/Portal2-32PlayerMod-Lite#1]
When leaving the level, the players get stuck in the tubes to return to the hub.  Players also get stuck if they're close (the spawn point is a good example of this.)  

Love the mod

**Comment by kyleraykbs** [comment]
Thanks for reporting this is currently our top priority

**Comment by kyleraykbs** [comment]
Fixed in Beta 1.1.0. Thanks for the help!
