### ISSUE TITLE
Issues with spawn

### ISSUE THREAD

**Issue by blimpey** [kyleraykbs/Portal2-32PlayerMod-Lite#2]
Hello, we're trying to run this with over 5 users.

We're able to host the server and I'm able to get everyone to join successfully. 

Issue: 
If more than 2 people are on the server, people will be stuck in the spawn and unable to enter any level. (Console would show Map Check) while we are stuck in spawn. 
- Similarly, once people complete a level, people are stuck in spawn and we have to return to hub to be able to continue player. The game behaves normally if it's just 2 people however, once a third player enters the world then everyone is stuck at spawn. 

Temporary workaround: 
-Have 2 users join the world and select the level and load in
-Once everyone gets to the end point , have everyone but the initial 2 players leave and complete the level. 
Rejoin once we're in the main lobby.

Other workaround:
-Have all players join the level after the initial 2 players enter the world
-Once completion, have anyone return to hub.

-Tried with 2 different hosts with the same results.

**Comment by kyleraykbs** [comment]
Thanks for reporting this is currently our top issue

**Comment by kyleraykbs** [comment]
Fixed in Beta 1.1.0. Thanks for the help!
