### ISSUE TITLE
Cross platform compatibility of mod

### ISSUE THREAD

**Issue by KonradCzerw** [kyleraykbs/Portal2-32PlayerMod-Lite#4]
Hello, is there any plans when it comes to porting the mod to linux and/or macos? I've already researched this field a bit but as far as i know this mod requires modification to the server .dll files which dissasembled yeild different results compared to the linux .so versions.

**Comment by kyleraykbs** [comment]
We plan to add support for linux (and possibly macos 50/50) within the next week! Stay tuned for updates!

**Comment by kyleraykbs** [comment]
If you would like to help write it that would be greatly appreciated if your willing to help please friend me on discord kyleraykbs#3230 (no pressure)

**Comment by KonradCzerw** [comment]
ok i think i got 16 player working (still no people to test with) but i have used the scripts and modified the binary in ghidra + hex editor thanks to a handy string reference to "-allowspectators" flag. When i tried to make it 32/33 players it crashed, but it might've been an error. I shot you a friend request on discord and i'll post you the results.

**Comment by akash-258** [comment]
Any update on this, can we get it to work on linux now ?
