### ISSUE TITLE
Can't get anymore than 3 players

### ISSUE THREAD

**Issue by tetTris11** [kyleraykbs/Portal2-32PlayerMod-Lite#5]
The server's max player count is always set to 3, thus denying connection to anymore players and I'm unable to set it any higher.
How does one go about this? or is it not supposed to do that?

**Comment by kyleraykbs** [comment]
It looks like the MultiplayerMod.cmd didnt install the server.dll correctly.
Friend me on discord so we can troubleshoot kyleraykbs#3230

**Comment by kyleraykbs** [comment]
Fixed In Dm's (Installed Incorrectly)
